const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://images.unsplash.com/photo-1587206668283-c21d974993c3?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://th.bing.com/th/id/R.537e56d1a3d77848bae45082dea2e5c3?rik=b9oM%2b1WpG452hA&riu=http%3a%2f%2ftransithotels.co.ke%2fwp-content%2fuploads%2f2016%2f01%2f5-Popular-Kenya-Dishes-for-Visitors.jpg&ehk=gFHREfrjMIjjNtTBMzvGDkqeYBoaOloo9q97aVmO7mk%3d&risl=&pid=ImgRaw&r=0',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://theurbantandoor.com/wp-content/uploads/2020/04/pulao.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://cdni.rbth.com/rbthmedia/images/2018.12/original/5c1a423e15e9f95a961de3dc.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://th.bing.com/th/id/OIP.ygGSIrnttMYdNUBOn95lZgHaE8?pid=ImgDet&w=1200&h=800&rs=1',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://i.pinimg.com/originals/bf/2b/49/bf2b49ef66f1a8c9b244b3ee63cc46c1.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://th.bing.com/th/id/OIP.QWeFwwIKCaf3oaxlUtwtJAHaD0?pid=ImgDet&rs=1',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://th.bing.com/th/id/OIP.7rGf-ur-hiDYkO-70sLuQgHaF7?pid=ImgDet&rs=1',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://th.bing.com/th/id/R.edfdf6594e2bf488b6dbfa2e48368ff8?rik=%2b4HZeYGiSZ8ygw&riu=http%3a%2f%2fwww.fuddruckers.ae%2fwp-content%2fuploads%2f2017%2f02%2fz6-5-683x1024.jpg&ehk=BWDk3XLw9jGNmc%2b2yqWMAk2EzOM0fqxm6zjUMJ2CUIw%3d&risl=&pid=ImgRaw&r=0',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;